# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

before:
  hooks:
    # - export NODE_OPTIONS="--max-old-space-size=8192"
    # - make build_web
    - chmod +x ./ci/script.sh
    - ./ci/script.sh
    - sed -i 's@ORIGINAL_VERSION=.*@ORIGINAL_VERSION=v{{ .Version }}@g' 1pctl
    - sed -i 's@/usr/bin/1panel@/usr/local/bin/1panel@g' 1panel.service
    - go get -u modernc.org/sqlite
    - go mod tidy

builds:
  - main: ./cmd/server/main.go
    binary: 1panel
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarm:
      - 6
      - 7
    goarch:
      - 386
      - amd64
      - arm64
      - arm
      - loong64
      - ppc64le
      - riscv64
      - s390x

archives:
  - format: tar.gz
    name_template: "1panel-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    files:
      - 1pctl
      - 1panel.service
      - install.sh
      - README.md
      - LICENSE
      - lang/*
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"